<div class="header-link col-md-3 col-sm-3 col-xs-9">
	<ul class="header-table">
		<li class="header-1 col-md-5 col-sm-5 col-xs-5"><a href="#"><?= /* @escapeNotVerified */ __('About Us') ?></a></li>
		<li class="header-2 col-md-3 col-sm-3 col-xs-3"><a href="#"><?= /* @escapeNotVerified */ __('Help') ?></a></li>
		<li class="header-3 col-md-4 col-sm-4 col-xs-4"><a href="#"><?= /* @escapeNotVerified */ __('Contact us') ?></a></li>
    </ul>
</div>