<div class="header-cake-link col-md-6 col-sm-5 col-xs-6">
    <ul>
        <li class="header-1 col-md-2 col-sm-2 col-xs-2">
        <?php
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header-link-1')
            ->toHtml();
        ?>
        </li>
        <li class="header-2 col-md-2 col-sm-2 col-xs-2">
        <?php
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header-link-2')
            ->toHtml();
        ?>
        </li>
        <li class="header-3 col-md-2 col-sm-2 col-xs-2">
        <?php
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header-link-3')
            ->toHtml();
        ?>
        </li>
        <li class="header-4 col-md-3 col-sm-3 col-xs-3">
        <?php
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header-link-4')
            ->toHtml();
        ?>
        </li>
        <li class="header-5 col-md-3 col-sm-3 col-xs-3">
        <?php
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header-link-5')
            ->toHtml();
        ?>
        </li>
    </ul>
</div>
<div>
<?php
    echo $this->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('hover-link')
    ->toHtml();
?>
</div>

<script type="text/javascript">
   require(['jquery'], function($) {
        $('.category-head').click(function(){
        $('#links').toggleClass('show-block');
    });
});
   </script>