<div>
    <form class="col-md-11 col-sm-11 col-xs-11" action="customer/account/login/referer" method="post">
        <input class="user" type="text" name="uname" placeholder=<?= /* @escapeNotVerified */ __('Username') ?>/><br>
        <input class="password" type="password" name="password" placeholder=<?= /* @escapeNotVerified */ __('Password') ?>/><br>
        <input class="submit" type="submit" value=<?= /* @escapeNotVerified */ __('SIGN IN') ?>/>
            <ul>
                <li><a href="<?= $this->getUrl('customer/account/create');?>"><?= /* @escapeNotVerified */ __('New User') ?></a></li>  
                <li><a href="<?= $this->getUrl('customer/account/forgotpassword');?>"><?= /* @escapeNotVerified */ __('Forget your password?') ?></a></li>  
        </ul>
     </form>
</div>