<?php
$categoryId = $block->getCategoryId();
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $_objectManager->create('Magento\Catalog\Model\Category')
->load($categoryId);
$categoryName= $category->getName();
$categoryDesc = $category->getDescription();
?>
<div class="name"><?= __($categoryName); ?></div>
<div class="description"><?= __($categoryDesc); ?></div>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
?>
<div class="bxslider cake-slider">
    <?php 
        foreach ($items as $_item) {
    ?>
    <div>
        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
            <?= $block->getImage($_item, $image)->toHtml() ?>
        </a>
        <div class="product-item-details text-center">
            <strong class="product-item-name">
                <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                   href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                   class="product-item-link">
                    <?= $block->escapeHtml($_item->getName()) ?>
                </a>
            </strong>
            <?php
                echo $block->getProductPriceHtml($_item, $type);
            ?>
        </div>
    </div>
    <?php
        }
    ?>      
</div>
<?php endif;?>