<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
<?php

    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
?>
<!-- <div>
        <img class="col-md-3 col-sm-3 col-xs-3" src="<?php echo $this->getViewFileUrl("images/watermark-left.jpg");?>"/>
        <img class="col-md-3 col-sm-3 col-xs-3" src="<?php echo $this->getViewFileUrl("images/watermark-right.jpg");?>"/>
        <div>
            <span><?= /* @escapeNotVerified */ __('PLATTERS') ?></span></span>
        </div>
    </div> -->
<div class="bxslider cake-slider">
    <?php 
        foreach ($items as $_item) {
    ?>
    <div>
        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
            <?= $block->getImage($_item, $image)->toHtml() ?>
        </a>
        <div class="product-item-details text-center">
            <strong class="product-item-name">
                <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                   href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                   class="product-item-link">
                    <?= $block->escapeHtml($_item->getName()) ?>
                </a>
            </strong>
            <?php
                echo $block->getProductPriceHtml($_item, $type);
            ?>
        </div>
    </div>
    <?php
        }
    ?>      
</div>
<?php endif;?>