<?php 

$helper = $this->helper('Excellence\ExcellenceSlider\Helper\Data');
$sliderStatus=$helper->isSliderEnabled();
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance 
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$sliderCollection = $helper->getSliderUrl();

if ($sliderStatus == '1'){ 
  ?>
  <div class="bxslider">
    <?php
      foreach($sliderCollection->getData() as $slide){
          ?>
          <div>
              <img src="<?php echo $mediaUrl.$slide['path']; ?>" title="GET A FREE DESSERT"/>
          </div>
          <?php
      }
    ?>
  </div>
<?php
}
?>
<script type="text/javascript" xml="space">
    require([
        'jquery',
        'bxSlider'
    ], function($){
        $(document).ready(function() {
            $('.bxslider').bxSlider( {
                controls: true,
                captions: true,
                slideWidth: 700
            });
        });
    });
</script>
