<div>
    fgrhfrd
</div>
<div>
<?php
        echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('cake')
        ->toHtml();
    ?>
</div>
<script type="text/javascript" xml="space">
    require([
        'jquery',
        'bxSlider'
    ], function($){
        $(document).ready(function() {
            $('.bxslider.cake-slider').bxSlider( {
                controls: true,
                captions: true,
                slideWidth: 300,  
                minSlides:3,
                maxSlides:3,
                moveSlides:3
            });
        });
    });
</script> 
<!-- <script type="text/javascript" xml="space">
    require([
        'jquery',
        'bxSlider'
    ], function($){
        $(document).ready(function() {
            $('.main-slider').bxSlider( {
                controls: true,
                captions: true,
                slideWidth: 700
            });
        });
    });
</script> -->