<!-- above link set pending -->
<div>
    <div class="column-2 women-catalog-slider" style="margin-top: -1%; font-family: 'Oswald', sans-serif;">
         <?php
            echo $this->getLayout()
              ->createBlock('Magento\Cms\Block\Block')
              ->setBlockId('women-s')
              ->toHtml();
          ?>
    </div>
</div>
<div style="width:100%; float:left; font-family: 'Oswald', sans-serif;" > 
    <div>
        <?php
            echo $this->getLayout()
              ->createBlock('Magento\Cms\Block\Block')
              ->setBlockId('men')
              ->toHtml();
          ?>
         </div>
    </div>

<script type="text/javascript" xml="space">
    require([
        'jquery',
        'bxSlider'
    ], function ($) {
        // 'use strict';
        // $.noConflict();

        //less-essential-slider
        $(document).ready(function() {
            $('.bxslider').bxSlider( {
                // controls: true,
                captions: true,
                slideWidth: 700
            });
        });

        //men-catalog-carousel
        $(document).ready(function() {
            $('.bxslider').bxSlider( {
                controls: true,
                captions: true,
                slideWidth: 700
            });
        });
    });
</script>